spring:
  datasource:
    url: jdbc:postgresql://localhost:5432//product_management
    username: postgres
    password: admin141592

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect